### ISSUE TITLE
Is possible to add to laravel app with pwa separate frontend??

### ISSUE THREAD

**Issue by Artessan** [classiebit/addchat-laravel#1]
Hi we are making a laravel api with a pwa separate front end and we are looking for something like this to make customer support. Is possible to integrate the chat in the pwa??

**Comment by classiebit** [comment]
Hii. So your frontend will be a Progressive Web App in which language? If it's in VueJs, 

- and somehow you can include the AddChat Laravel JS & CSS files into your PWA
- and if you can add the AddChat widget code into your app

Then it may be possible.
