### ISSUE TITLE
Site not loading conversations and messages properly

### ISSUE THREAD

**Issue by saswatp99** [classiebit/addchat-laravel#10]
Whenever a new message arrives, the site is stuck at that point. The notification comes but there is no option to open the new message. Also, the conversation is stuck again and again. Please check for the same.

**Comment by classiebit** [comment]
That might be the issue with your hosting, or website's other JavaScript packages or codes.

**Comment by classiebit** [comment]
You can check out the live demo for the same.- https://addchat-laravel.classiebit.com
