### ISSUE TITLE
addchat:install run showing error

### ISSUE THREAD

**Issue by dhruv1998** [classiebit/addchat-laravel#11]
Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in D:\laragon\www\chatmic\vendor\classiebit\addchat-laravel\src\Commands\InstallCommand.php on line 81

**Comment by classiebit** [comment]
Which Laravel version you're installing it with? And what's your PHP version?

**Comment by dhruv1998** [comment]
I am using laravel 8 and php versions 7.4

**Comment by classiebit** [comment]
@dhruv1998 Issue resolved @v1.0.6 Resolve install command issue patch.
