### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by AndreFabris** [classiebit/addchat-laravel#2]
On both my development site and your demo site, in the browser console you get:
Request URL:http://www.appsforce.com/undefined/addchat/img/addchat-shadow.png
Request method:GET
Remote address:127.0.0.1:80
Status code:
404
Version:HTTP/1.0

**Comment by classiebit** [comment]
Hi, this happens just for the first request, and it doesn't affect anything. So you can ignore this one.
