### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by AndreFabris** [classiebit/addchat-laravel#3]
If you are in Netherlands (UTC+1), the timestamp in the chat are +60min.
I can see that they are recorded in the database as UTC+0
Same happens on your demo site

**Comment by classiebit** [comment]
Hi, You need to change your Laravel website default timezone, because AddChat Laravel detects timezone from the website where it's installed.

**Comment by AndreFabris** [comment]
Ok, that works, thank you
