### ISSUE TITLE
Fontawesome 5.0 overrides 4.7

### ISSUE THREAD

**Issue by AndreFabris** [classiebit/addchat-laravel#4]
In your CSS you are using Fontawesome 5.0 Free
#addchat-bot-admin .c-top-menu span.c-closed
{
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
}
When this is enabled it overrides my site which is using 4.7. 
Disabling this removes all icons from the widget

**Comment by classiebit** [comment]
Hi, AddChat Laravel CSS has wrapped its own wrapper, so it won't affect your website CSS. If you're having this issue, just put your website CSS file in the last, e.g 

1. AddChat CSS
2. Your website CSS

After this, your website CSS will have top priority over all other CSS files.

**Comment by AndreFabris** [comment]
Ok that got it sorted, thx
