### ISSUE TITLE
Issue/Feature Request

### ISSUE THREAD

**Issue by AndreFabris** [classiebit/addchat-laravel#5]
Hi,
I like the product, finally got it the way I wanted it (using live presence and images defined in user profile and not the ones in the widget).

However, it should detect keyboard Enter (or Shift Enter) to send message. It is very annoying to type, and then have to use mouse..
Thanks,
Andre

**Comment by classiebit** [comment]
Hi, thank you so much for appreciating. And the good news is, we're already working on the next version and is almost complete, and the new version will come with some design changes, enter to send button and a few more advanced features.

And also, we've made changes in the Laravel API as well, converted single controller into multiple, and converted database queries into Eloquent queries.

And also simplified the installation process, and a lot more.

Just give us a few more time, we'll be releasing it max before end of Jan-2020.

Thank you

**Comment by classiebit** [comment]
Enter to send message feature added in v1.1.0 in the addchat-laravel-pro version.
