### ISSUE TITLE
How to configure default user without showing users lists in chat box

### ISSUE THREAD

**Issue by srikanth240369** [classiebit/addchat-laravel#7]
How to configure default user without showing users lists in chat box

**Comment by classiebit** [comment]
We've added this feature in AddChat Laravel Pro - https://classiebit.com/addchat-laravel-pro

You can read about the feature in the docs - https://addchat-laravel-pro-docs.classiebit.com/docs/1.1/features/external-button

With this feature, you can set a callback JS function on any button with the **user-id** and it'll open the user as default to chat with.
