### ISSUE TITLE
Laravel 7 compatibility?

### ISSUE THREAD

**Issue by computer-logix** [classiebit/addchat-laravel#8]
I just updated my site to Laravel 7.6.2 and came across this application.   It was a no-brainer and I was planning to purchase the Pro version but I can't get the lite version to work first.

Will you be adding Laravel 7 compatibility soon because I can't go back to version 6 at this time.
Do you have a beta in the works?

$ php artisan addchat:install
Initiate the installation process...
1. Publishing Addchat core assets: config & languages
Copied Directory [\vendor\classiebit\addchat-laravel\publishable\lang] To [\resources\lang\vendor\addchat]
Copied Directory [\vendor\classiebit\addchat-laravel\publishable\assets] To [\public\assets]
Publishing complete.
2. Migrating the Addchat database tables into your application
Nothing to migrate.
---- Dumping the autoloaded files and reloading all new files ----

   TypeError 

  Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in C:\repositories\portal.git\develop.melloul-blamey.construction.local\vendor\classie
bit\addchat-laravel\src\Commands\InstallCommand.php on line 81

  at C:\repositories\portal.git\develop.melloul-blamey.construction.local\vendor\symfony\process\Process.php:140
    136|      * @param int|float|null $timeout The timeout in seconds or null to disable
    137|      *
    138|      * @throws LogicException When proc_open is not installed
    139|      */
  > 140|     public function __construct(array $command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)
    141|     {
    142|         if (!\function_exists('proc_open')) {
    143|             throw new LogicException('The Process class relies on proc_open, which is not available on your PHP installation.');
    144|         }

  1   C:\repositories\portal.git\develop.melloul-blamey.construction.local\vendor\classiebit\addchat-laravel\src\Commands\InstallCommand.php:81
      Symfony\Component\Process\Process::__construct("composer dump-autoload")

  2   C:\repositories\portal.git\develop.melloul-blamey.construction.local\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32
      Classiebit\Addchat\Commands\InstallCommand::handle(Object(Illuminate\Filesystem\Filesystem))
`

**Comment by classiebit** [comment]
Hi,

For now, it's compatible up to Laravel 6.x. and 6.x is also LTS version as of now. And in the next upcoming updates (maybe next month), we'll make it compatible with Laravel 7.x.

**Comment by computer-logix** [comment]
I'll be waiting patiently.    Unfortunately I found your product an hour 
after implementing our Laravel 7 update.
I'll be happy to test any Beta or RC versions on my development version. 
   (not production obviously)

Thanks.

------ Original Message ------

**Comment by classiebit** [comment]
Yes, Laravel 7 is much more advanced and uses Latest PHP & MySql version. So, if you're planning to deploy your project to any shared or CPANEL hosting, then it's 99% chances, that it won't work.

Hence, it's recommended to use up to Laravel 6.x, if you're going to deploy on shared hosting.

And that's why we're not making it compatible with Laravel 7.x. Because, if we add support for 7.x then we will need to remove support for Laravel 5.x versions. 

And 90% of existing Laravel websites are still running in 5.x versions. So it won't be a good decision, for now, to make it compatible with Laravel 7.x.

We hope you're getting the point.

**Comment by aqshah20** [comment]
I have just  changed 1 line in installcommand.php file now its working fine in laravel 7.x

**Comment by yestif** [comment]
> I have just changed 1 line in installcommand.php file now its working fine in laravel 7.x

Would you please tell us the line you changed to make this work in laravel 7.x ??

**Comment by glupeksha** [comment]
@jqsys what did you do?

changed line 81 in installCommand.php to
`$process = new Process([$composer.' dump-autoload']);` ?

**Comment by Himashukla** [comment]
I'm also facing the same error. Is there any solution?

**Comment by classiebit** [comment]
@upeksha1996 Issue resolved @v1.0.6 Resolve install command issue patch.
